Data from https://docs.google.com/spreadsheets/d/1hTs_PB7KuTMBtNMESFEGuK-0abzhNxVv4tgpI5-iKe8/edit#gid=1171606318

In [25]:
import pandas as pd
import os.path

dirname = 'banned_book_data'
filename = "PEN America's Index of School Book Bans (July 1, 2021 - June 30, 2022) - Sorted by Author & Title.csv"
os.chdir('/Users/gawron/Desktop/src/sphinx/python_for_ss_extras/colab_notebooks/python-for-social-science-solutions')
url = os.path.join(dirname,filename)
df = pd.read_csv(url,header=2)

In [42]:
gg0 = df.groupby('State')
ban_counts0 = gg0['Title'].count()
ban_counts0.sort_values(ascending=False)[:15]

State
Texas             801
Florida           566
Pennsylvania      458
Tennessee         349
Oklahoma           43
Michigan           41
Kansas             30
Wisconsin          29
Missouri           27
Idaho              26
Georgia            23
Mississippi        22
Virginia           19
Indiana            18
North Carolina     16
Name: Title, dtype: int64

In [38]:
gg = df.groupby(['State','District'])
ban_counts = gg['Title'].count()
ban_counts.sort_values(ascending=False)

State         District
Pennsylvania  Central York School District              441
Texas         North East Independent School District    435
Tennessee     Collierville Schools                      327
Florida       Duval County Public Schools               176
              Indian River County School District       161
                                                       ...
Rhode Island  Pawtucket School Department                 1
Pennsylvania  Wissahickon School District                 1
              Kutztown Area School District               1
              Franklin Regional School District           1
Alaska        Anchorage School District                   1
Name: Title, Length: 138, dtype: int64

In [140]:
ban_counts.loc['Pennsylvania']

District
Central York School District                441
Downingtown Area School District              3
East Stroudsburg Area School District         2
Eastern Lancaster County School District      1
Elizabethtown Area School District            1
Fairview School District                      1
Franklin Regional School District             1
Kutztown Area School District                 1
North Penn School District                    3
Pennridge School District                     3
Wissahickon School District                   1
Name: Title, dtype: int64

In [144]:
ban_counts.loc['Texas'].sort_values(ascending=False)

District
North East Independent School District            435
Granbury Independent School District              133
Katy Independent School District                   45
Fredericksburg Independent School District         42
Klein Independent School District                  35
Prosper Independent School District                23
Cypress-Fairbanks Independent School District      16
Birdville Independent School District              14
Keller Independent School District                 11
Leander Independent School District                11
Lamar Consolidated Independent School District      7
Clear Creek Independent School District             7
Frisco Independent School District                  7
Killeen Independent School District                 4
Richardson Independent School District              2
Spring Branch Independent School District           2
Tyler Independent School District                   2
Lake Travis Independent School District             1
Canutillo Independent School District               1
Fort Bend ISD                                       1
Denton Independent School District                  1
Waller Independent School District                  1
Name: Title, dtype: int64

In [27]:
df

,Author,Title,Type of Ban,Secondary Author(s),Illustrator(s),Translator(s),State,District,Date of Challenge/Removal,Origin of Challenge
0,"Àbíké-Íyímídé, Faridah",Ace of Spades,Banned in Libraries and Classrooms,NaN,NaN,NaN,Florida,Indian River County School District,November 2021,Administrator
1,"Acevedo, Elizabeth",Clap When You Land,Banned in Classrooms,NaN,NaN,NaN,Pennsylvania,Central York School District,August 2021,Administrator
2,"Acevedo, Elizabeth",The Poet X,Banned in Libraries,NaN,NaN,NaN,Florida,Indian River County School District,November 2021,Administrator
3,"Acevedo, Elizabeth",The Poet X,Banned in Libraries and Classrooms,NaN,NaN,NaN,New York,Marlboro Central School District,February 2022,Administrator
4,"Acevedo, Elizabeth",The Poet X,Banned Pending Investigation,NaN,NaN,NaN,Texas,Fredericksburg Independent School District,March 2022,Administrator
...,...,...,...,...,...,...,...,...,...,...
2527,"Zia, Farhana",The Garden of My Imaan,Banned Pending Investigation,NaN,NaN,NaN,Florida,Duval County Public Schools,January 2022,Administrator
2528,"Ziemke, Kristin",Read the World: Rethinking Literacy for Empath...,Banned in Classrooms,"Muhtaris, Katie",NaN,NaN,Pennsylvania,Central York School District,August 2021,Administrator
2529,"Zoboi, Ibi",American Street,Banned in Classrooms,NaN,NaN,NaN,Pennsylvania,Pennridge School District,August 2021,Administrator
2530,"Zoboi, Ibi",Black Enough: Stories of Being Young & Black i...,Banned in Libraries,NaN,NaN,NaN,Florida,Indian River County School District,November 2021,Administrator
2531,"Zunon, Elizabeth","Grandpa Cacao: A Tale of Chocolate, from Farm ...",Banned in Classrooms,NaN,NaN,NaN,Pennsylvania,Central York School District,August 2021,Administrator

In [54]:
df['District'].value_counts()

Central York School District                 441
North East Independent School District       435
Collierville Schools                         327
Duval County Public Schools                  176
Indian River County School District          161
                                            ...
Regional School Unit No. 56                    1
Connetquot Central School District             1
Wappingers Central School District             1
Fairview School District                       1
Lower Township Elementary School District      1
Name: District, Length: 138, dtype: int64

In [26]:
df['State'].value_counts()

Texas             801
Florida           566
Pennsylvania      458
Tennessee         349
Oklahoma           43
Michigan           41
Kansas             30
Wisconsin          29
Missouri           27
Idaho              26
Georgia            23
Mississippi        22
Virginia           19
Indiana            18
North Carolina     16
New York           13
Utah               12
Iowa                8
Illinois            5
South Dakota        5
Washington          5
Ohio                4
New Jersey          3
Minnesota           1
Maryland            1
Vermont             1
Alaska              1
Rhode Island        1
Maine               1
South Carolina      1
Arkansas            1
Oregon              1
Name: State, dtype: int64

In [14]:
os.chdir('/Users/gawron/Desktop/src/sphinx/python_for_ss_extras/colab_notebooks/python-for-social-science-solutions')

Some party membership data for governors to turn into a CSV file.

In [132]:
#Data from https://www.nga.org/wp-content/uploads/2023/01/2023-Governors-Roster.pdf
df = pd.read_csv(path,header=2)

In [133]:
non_states = ['American Samoa','Northern Mariana Is.','Puerto Rico','Virgin Islands','Guam']
states0 = df[~(df['State/Jurisdiction'].isin(non_states))]
states = states0.rename(columns={"State/Jurisdiction":'State'})
states.index = range(50)

In [134]:
states

,State,Governor,Affiliation,Present Term Began,Present Term Ends,Previous Terms,Maximum Consecutive Terms
0,Alabama,Kay Ivey,(R),1-23,1-27,1+(g),2
1,Alaska,Mike Dunleavy,(R),12-22,12-26,1,2
2,Arizona,Katie Hobbs,(D),1-23,1-27,NaN,2
3,Arkansas,Sarah Huckabee Sanders,(R),1-23,1-27,NaN,2
4,California,Gavin Newsom,(D),1-23,1-27,1,2
5,Colorado,Jared Polis,(D),1-23,1-27,1,2
6,Connecticut,Ned Lamont,(D),1-23,1-27,1,NaN
7,Delaware,John Carney,(D),1-21,1-25,1,2(a)
8,Florida,Ron DeSantis,(R),1-23,1-27,1,2
9,Georgia,Brian Kemp,(R),1-23,1-27,1,2
10,Hawaii,Josh Green,(D),12-22,12-26,NaN,2
11,Idaho,Brad Little,(R),1-23,1-27,1,NaN
12,Illinois,JB Pritzker,(D),1-23,1-27,1,NaN
13,Indiana,Eric Holcomb,(R),1-21,1-25,1,2(b)
14,Iowa,Kim Reynolds,(R),1-23,1-27,1+(h),NaN
15,Kansas,Laura Kelly,(D),1-23,1-27,1,2
16,Kentucky,Andy Beshear,(D),12-19,12-23,NaN,2
17,Louisiana,John Bel Edwards,(D),1-20,1-24,1,2
18,Maine,Janet Mills,(D),1-23,1-27,1,2
19,Maryland,Wes Moore,(D),1-23,1-27,NaN,2
20,Massachusetts,Maura Healey,(D),1-23,1-27,NaN,NaN
21,Michigan,Gretchen Whitmer,(D),1-23,1-27,1,2
22,Minnesota,Tim Walz,(D),1-23,1-27,1,NaN
23,Mississippi,Tate Reeves,(R),1-20,1-24,NaN,2
24,Missouri,Mike Parson,(R),1-21,1-25,1+(i),2
25,Montana,Greg Gianforte,(R),1-21,1-25,NaN,2(c)
26,Nebraska,Jim Pillen,(R),1-23,1-27,NaN,2(b)
27,Nevada,Joe Lombardo,(R),1-19,1-23,NaN,2
28,New Hampshire,Chris Sununu,(R),1-23,1-25(d),3,NaN
29,New Jersey,Phil Murphy,(D),1-22,1-26,1,2
30,New Mexico,Michelle Lujan Grisham,(D),1-23,1-27,1,2
31,New York,Kathy Hochul,(D),1-23,1-27,(k),NaN
32,North Carolina,Roy Cooper,(D),1-21,1-25,NaN,2
33,North Dakota,Doug Burgum,(R),12-20,12-24,NaN,NaN
34,Ohio,Mike DeWine,(R),1-23,1-27,1,2(b)
35,Oklahoma,Kevin Stitt,(R),1-23,1-27,1,2
36,Oregon,Tina Kotek,(D),1-23,1-27,NaN,2
37,Pennsylvania,Josh Shapiro,(D),1-23,1-27,NaN,2
38,Rhode Island,Dan McKee,(D),1-23,1-27,(j),2
39,South Carolina,Henry McMaster,(R),1-23,1-27,1+(f),2
40,South Dakota,Kristi Noem,(R),1-23,1-27,1,2
41,Tennessee,Bill Lee,(R),1-23,1-27,1,2
42,Texas,Greg Abbott,(R),1-23,1-27,2,NaN
43,Utah,Spencer Cox,(R),1-21,1-25,NaN,NaN
44,Vermont,Phil Scott,(R),1-23,1-25(d),2,NaN
45,Virginia,Glenn Youngkin,(R),1-22,1-26,NaN,(e)
46,Washington,Jay Inslee,(D),1-21,1-25,2,NaN
47,West Virginia,Jim Justice,(R),1-21,1-25,1,2
48,Wisconsin,Tony Evers,(D),1-23,1-27,1,NaN
49,Wyoming,Mark Gordon,(R),1-23,1-27,1,2

In [135]:
states['Affiliation'].value_counts()

(R)    26
(D)    24
Name: Affiliation, dtype: int64